version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ofauto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ofauto
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=demo-jwt-secret
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
    ports:
      - "4000:4000"
    command: sh -c "npm ci && npm run db:migrate && npm run db:seed && npm run dev"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    command: sh -c "npm ci && npm run dev"

volumes:
  postgres_data:
  redis_data: 