version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ofauto_db
    restart: always
    environment:
      POSTGRES_DB: ofauto
      POSTGRES_USER: ofauto_user
      POSTGRES_PASSWORD: very_strong_password123! # <- CHANGE THIS IN PRODUCTION
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 4g

volumes:
  postgres_data:
    driver: local 